---
- name: Insall apache and php
  hosts: webserver
  become: yes
  tasks:
    - name: information about node and variables loaded
      debug:
        msg: "node os is {{ ansible_facts['distribution'] }} package name is {{package}} and info location is {{info_Location}} and php packages are {{php_package}}"
    - name: fail on unsupported
      fail:
        msg: This playbook supports only RedHat 8 and ubuntu 18
      when:
        - ansible_facts['distribution'] != "RedHat"
        - ansible_facts['distribution'] != "ubuntu"
        - (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] != "8")
        - (ansible_facts['distribution'] == "ubuntu" and ansible_facts['distribution_major_version'] != "18")
    - name: install apache
      package:
        name: "{{package}}"
        state: present
    - name: install httpd
      package:
        name: "{{package}}"
        state: present
    - name: create info.php
      copy:
        dest: "{{ info_Location }}"
        content: |
          <?php
          phpinfo();
          ?>
      notify: Restart apache
    - name: Restart apache
      service:
        name: "{{package}}"
        enabled: yes
        state: restarted
